name = "asmr-collections"
main = "cloudflare/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat", "nodejs_compat_populate_process_env" ]

[vars]
RUNTIME = "workers"

[assets]
directory = "./dist"
binding = "ASSETS"

[env.production]
name = "asmr-collections"
workers_dev = true

[env.production.vars]
RUNTIME = "workers"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true